version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "publish"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "specmore/spectacular-helm"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  publish:
      title: Publish Helm Chart
      type: helm
      stage: publish
      working_directory: ./spectacular-helm
      arguments:
        action: push
        chart_name: spectacular