apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: spectacular-auth-{{.Release.Name}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spectacular-auth-{{.Release.Name}}
    spec:
      containers:
        - name: spectacular-auth-{{.Release.Name}}
          image: tarent/loginsrv:latest
          ports:
            - containerPort: 8080
          env:
            {{- if not (or .Values.managedCertificate .Values.clusterIssuer) }}
            - name: LOGINSRV_COOKIE_SECURE
              value: "false"
            {{- end }}
            - name: LOGINSRV_GITHUB
              valueFrom:
                secretKeyRef:
                  name: github-oauth-{{.Release.Name}}
                  key: oauth-config
            - name: LOGINSRV_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-keys-{{.Release.Name}}
                  key: shared-signing-key
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: spectacular-backend-{{.Release.Name}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spectacular-backend-{{.Release.Name}}
    spec:
      containers:
        - name: spectacular-backend-{{.Release.Name}}
          {{- if .Values.releaseCandidateTag }}
          image: specmore/spectacular-backend-release-candidate:{{ .Values.releaseCandidateTag }}
          {{- else }}
          image: specmore/spectacular-backend:0.2.2
          {{- end }}
          ports:
            - containerPort: 80
          env:
            - name: GITHUB_APP_PRIVATE_KEY_FILE_PATH
              value: "/usr/spectacular/private-key.pem"
            - name: GITHUB_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: github-app-config-{{.Release.Name}}
                  key: app-id
            - name: JWT_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-keys-{{.Release.Name}}
                  key: shared-signing-key
          volumeMounts:
            - name: private-key-volume
              mountPath: "/usr/spectacular/"
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
      - name: private-key-volume
        secret:
          secretName: github-app-{{.Release.Name}}
          items:
          - key: private-key.pem
            path: private-key.pem
---
apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: spectacular-web-{{.Release.Name}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spectacular-web-{{.Release.Name}}
    spec:
      containers:
        - name: spectacular-web-{{.Release.Name}}
          {{- if .Values.releaseCandidateTag }}
          image: specmore/spectacular-web-release-candidate:{{ .Values.releaseCandidateTag }}
          {{- else }}
          image: specmore/spectacular-web:0.2.2
          {{- end }}
          ports:
            - containerPort: 80
          env:
            - name: API_LOCATION
              value: "http://spectacular-backend-{{.Release.Name}}"
            - name: AUTH_LOCATION
              value: "http://spectacular-auth-{{.Release.Name}}"
            - name: GITHUB_APP_INSTALLATION_ID
              valueFrom:
                configMapKeyRef:
                  name: github-app-config-{{.Release.Name}}
                  key: installation-id
          command: ["/bin/sh"]
          args: ["-c", "envsubst '$${API_LOCATION},$${AUTH_LOCATION},$${GITHUB_APP_INSTALLATION_ID}' < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
