apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spectacular-ingress-{{.Release.Name}}
  {{ if or .Values.managedCertificate }}
  annotations:
    {{ if .Values.managedCertificate }}
    networking.gke.io/managed-certificates: {{ .Values.managedCertificate | quote  }}
    {{ end }}
  {{ end }}
spec:
  backend:
    serviceName: spectacular-web-{{.Release.Name}}
    servicePort: 80