apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spectacular-ingress-{{.Release.Name}}
  {{ if or .Values.managedCertificate .Values.staticIpName }}
  annotations:
    {{ if .Values.staticIpName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.staticIpName | quote  }}
    {{ end }}
    {{ if .Values.managedCertificate }}
    networking.gke.io/managed-certificates: {{ .Values.managedCertificate | quote  }}
    kubernetes.io/ingress.allow-http: "false"
    {{ end }}
  {{ end }}
spec:
  backend:
    serviceName: spectacular-web-{{.Release.Name}}
    servicePort: 80