apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spectacular-ingress-{{.Release.Name}}
  {{ if .Values.managedCertificate }}
  annotations:
    networking.gke.io/managed-certificates: {{ .Values.managedCertificate | quote  }}
    kubernetes.io/ingress.allow-http: "false"
  {{ end }}
spec:
  backend:
    serviceName: spectacular-web-{{.Release.Name}}
    servicePort: 80