apiVersion: v1
data:
  shared-signing-key: {{ default (randAlphaNum 32) .Values.authJwtSharedSecret | b64enc }}
kind: Secret
metadata:
  name: auth-keys-{{.Release.Name}}
type: Opaque
---
apiVersion: v1
data:
  oauth-config: >-
    {{ printf "client_id=%s,client_secret=%s" .Values.githubClientId .Values.githubClientSecret | b64enc }}
kind: Secret
metadata:
  name: github-oauth-{{.Release.Name}}
type: Opaque
---
apiVersion: v1
data:
  app-id: NDgxMDU=
  private-key.pem: >-
    {{ required "A githubAppPrivateKey value is required!" .Values.githubAppPrivateKey | b64enc }}
kind: Secret
metadata:
  name: github-app-{{.Release.Name}}
type: Opaque
